from pathlib import Path
import re,json,csv,hashlib,html,collections
root=Path('/Users/timboi/Documents/Codex/2026-09-05'); out=root/'afm-classroom'
# Manual coding from each original question's requirements. Tags are teaching classifications.
rows=[
('SP','Specimen_From_September_2022',1,[
('Kingtim','Capital and valuation','WACC; bond pricing; beta; takeover defence; remuneration','Price new bonds with term-specific spot yields, then estimate post-tax debt cost and revised WACC. Evaluate shareholder reactions and employee pay.','Using book debt or one spot rate for all coupons.','Existing WACC, new bond value and revised WACC, then a board recommendation.'),
('Colvin','Investment','International NPV; PPP; tax; country risk','Build remittable overseas cash flows plus home contribution. Compare NPV at the requested risk-adjusted rate with the unadjusted rate.','Double counting transfer income or taxing losses immediately when they must be carried forward.','Cash-flow timeline in CL and euros, two NPVs and a critique of the risk premium.'),
('Boullain','Treasury','FX forwards; futures; options; margin','Compare receipt hedges including residual forward cover. Explain the value of a communicated hedging policy and margin liquidity.','Rounding contrary to the explicit round-down instruction.','EUR receipt for each strategy, contract count, premium and residual cover.')]),
('S22','September_2022',1,[
('Para Fuels','Investment','NPV; real options; ethics','Compare traditional and new technology before and after the sale option, then address board comments.','Adding sale proceeds and the option value for the same benefit.','Two base NPVs, an abandonment-option adjustment and a conditional recommendation.'),
('Lough','Treasury','Netting; FX hedging; treasury organisation','Tabulate group settlements and minimise the Swedish supplier payment. Weigh central and local treasury decisions.','Netting balances without first converting to one currency.','A net settlement table, comparative supplier costs and a treasury discussion.'),
('Felinhen','Capital and valuation','Restructuring; scenario valuation','Value the woodcraft business in all three scenarios and compare the available courses of action.','Recommending one scenario without evaluating the other disposal or recovery choices.','Three valuations, commercial implications and an explicit recommended course.')]),
('D22','December_2022',1,[
('Fondir','Treasury','FX forward; OTC option; IR futures; economic risk','Compare receipt hedges and the interest return under futures. Answer the board’s margin and risk-policy queries.','Confusing falling overseas competitiveness with a contracted transaction exposure.','USD receipts, investment return, futures gain/loss and a board report.'),
('Propleis / Adictcan','Acquisitions','Combined equity value; synergies; integration','Estimate combined equity and acquirer benefit. Challenge synergy assumptions and plan integration.','Equating all combined-company value with acquisition benefit.','Value bridge, acquirer gain and specific integration actions.'),
('Tonpantau','Investment','NPV; real options; BSOP limitations','Evaluate the investment and explain how real options extend the NPV decision in this case.','Describing BSOP assumptions without explaining how they affect this project.','NPV decision plus project-specific flexibility and valuation limitations.')]),
('P1','Practice_Exam_1',1,[
('Talam','Investment','NPV; expansion option; abandonment option; ethics','Calculate Uwa NPV, explain the Jigu asset value and value Honua’s offer. Address sustainability and child-labour issues.','Treating Jigu’s $10m future NPV as the option’s underlying asset value.','Base project valuation, separate option workings and an ethical response.'),
('Hav / Strand','Acquisitions','Synergy; excess earnings; PE; convertible offer','Compare premium valuations based on excess earnings and combined value. Evaluate cash and convertible payment.','Comparing a bond’s nominal amount with cash without a valuation basis.','Two premium ceilings, per-share payment comparison and seller preference.'),
('Lurgshall','Treasury','IR options; FRA; futures; swap','Compare options and the swap with the supplied FRA and futures rates. Critique the CEO’s view of treasury staffing.','Forgetting each party’s swap fee or the six-month exposure adjustment.','Effective loan rates, a swap cash-flow schedule and treasury value.')]),
('MJ23','March_June_2023',2,[
('Joshua','Acquisitions','WACC; FCFF; share exchange; dividends; agency','Estimate post-acquisition WACC and value, then gains and dividends for both groups. Evaluate defence motives and buyback.','Using the old share count after a share exchange.','Valuation and ownership bridge, dividend effects and an agency critique.'),
('Oxwick / Ludham','Acquisitions','Combined valuation; shareholder gain; assumptions','Test whether the acquisition meets the acquirer’s 15% wealth-gain requirement and challenge the director’s views.','Using target premium as the acquirer’s percentage gain.','Combined equity, acquirer percentage gain against 15% and assumptions.'),
('Blackbosca','Investment','International NPV; cash-flow critique; business risk','Evaluate the overseas project while challenging the consultant’s estimates and distinguishing business and financial risk.','Accepting the consultant’s figures without considering the CEO’s specific concerns.','Adjusted investment analysis and scenario-linked risk discussion.')]),
('SD23','September_December_2023',2,[
('McKeever','Investment','International NPV; PPP; sensitivity; country risk','Convert overseas flows, calculate dollar NPV and test the alternative exchange assumption. Address political and discount-rate risk.','Reversing the inflation ratio for a stated exchange-rate quotation.','Local flow schedule, dollar NPV, alternative case and supported recommendation.'),
('Southmed','Performance','Ratios; trends; financial strategy','Evaluate business situation and financial performance using ratios and trends. Identify useful missing information.','Listing ratio changes without explaining competitive or financing implications.','Calculated evidence, business explanation, financing implication and data gaps.'),
('Abertafol','Treasury','IR loan hedge; investment hedge; FRA; options','Advise separately on the $24m loan and $18m investment and answer each director’s query.','Using the same derivative direction for a borrower and a depositor.','Two exposure-specific comparisons with results and explanations.')]),
('MJ24','March_June_2024',2,[
('Mahoney','Treasury','Netting; FX futures; currency swap; NPV; trade policy','Calculate group settlements and divestment hedges, then compare project NPVs under swap and option cover.','Ignoring unhedged or overhedged balances and different coverage of final-year cash flow.','Settlement table, hedge comparison, two NPVs and trade-policy discussion.'),
('Littlebredy','Investment','NPV; expansion option; diversification; reporting','Evaluate office pods and the schools/universities option, then discuss diversification and strategy reporting.','Discounting the option exercise price at the project WACC in BSOP.','Base NPV, option calculation, decisions and investment reporting advice.'),
('Garnod','Acquisitions','FCFE; gain allocation; takeover defence','Analyse both targets. Calculate the target minimum and price allocating 60% of gains to the acquirer. Evaluate defence strategies.','Confusing share of total synergy with percentage gain on the acquirer’s equity.','Target minimum, FCFE valuation, gain split and separate defence discussion.')]),
('P2','Practice_Exam_2',2,[
('Lahla / Kawa','Acquisitions','Demerger; valuation; capital structure; regulation','Value demerged Kawa and the combination. Compare shareholder gains and capital structures for each payment method.','Discussing acquisition regulation without identifying affected stakeholders.','Standalone price, combination value, offer matrix and capital-structure discussion.'),
('Robson','Investment','APV; subsidy; issue costs; financing','Calculate APV and assess whether external shareholders and the subsidy provider will approve funding.','Charging finance costs in operating cash flows and again in APV adjustments.','Ungeared NPV, financing-benefit schedule and funding feasibility.'),
('Gogarth','Treasury','FX hedging; economic risk','Recommend a hedge for August dollar flows and explain treasury’s role in economic exposure.','Hedging gross receipts and payments separately when eligible net flows matter.','Comparable home-currency outcomes and an economic-risk response.')]),
('SD24','September_December_2024',3,[
('Northney','Treasury','Netting; FX futures; IR collar; political risk','Assess group treasury organisation, tabulate settlements, demonstrate FX and collar hedges and evaluate a new subsidiary.','Omitting the written option payoff or net premium from a collar.','Settlement table, FX result, two collar scenarios and subsidiary risk analysis.'),
('Mortexa / Yekkon','Acquisitions','Equity valuation; exchange offer; competition','Estimate equity and acquisition value, both groups’ wealth and majority-holder EPS. Evaluate approval and competition scrutiny.','Treating EPS improvement as proof of wealth creation.','Value and ownership bridge, EPS effect and competition factors.'),
('Zulla','Capital and valuation','DDM; FCFE; IPO; reverse takeover','Value equity using dividends and free cash flows, compare their suitability and assess reverse takeover versus IPO.','Assuming low early dividends imply low business value.','Two equity estimates, method critique and route-to-listing comparison.')]),
('MJ25','March_June_2025',3,[
('Kampai / Skal','Acquisitions','PE; combined equity; cash offer; share exchange; ESG','Estimate value and gains under cash and shares, then discuss financing, a mixed offer and factory closure.','Applying the old acquirer price to new shares without valuing the enlarged group.','Offer comparison for both groups, financing judgement and closure response.'),
('Sohbet','Treasury','IR futures; IR options; OTC versus traded','Calculate hedge results at a 3.8% base rate and justify futures/options or other choices. Compare OTC and traded options.','Selecting solely on a forecast rate while ignoring uncertainty and premium.','Net interest outcomes, recommendation and instrument suitability.'),
('GCR','Performance','Ratios; investor returns; funding; franchise risk','Evaluate financial performance and position from company and investor perspectives, with missing information.','Ignoring threatened franchise renewal when interpreting current financial ratios.','Trend and ratio evidence, investor consequences and essential data gaps.')]),
('SD25','September_December_2025',3,[
('Drimpton','Investment','International NPV; trade area; ESG','Evaluate the Edricer investment and trade-area advantages. Discuss assumptions and recommend ESG actions.','Omitting parent cash flows or turning the ESG requirement into generic definitions.','International NPV, financial recommendation and scenario-specific ESG actions.'),
('Halstock / Marnhall','Acquisitions','Synergy scenarios; shareholder gains; integration','Compare acquirer share gains with and without synergies, challenge estimates and address integration barriers.','Presenting synergies as certain rather than testing the no-synergy scenario.','Two wealth outcomes, sceptical evaluation and practical barrier-removal actions.'),
('Passmore','Treasury','FX receipt hedging; treasury contribution','Compare hedges for the R202m receipt and discuss treasury’s positive financial contribution.','Recommending a hedge without net proceeds or the decision factors.','Hedge workings, net proceeds and treasury activities linked to financial value.')]),
('MD25','Pre_December_2025_Mock_Exam',3,[
('TAS','Investment','International NPV; sale offer; trade tariffs; risk','Value the project before and after NDT’s offer, explain assumptions, business risks and tariff effects.','Counting an entire disposal receipt as incremental value without considering surrendered flows.','Two project values, a conditional decision and trade/business risk discussion.'),
('Sheakam','Treasury','IR investment; futures; options; policy','Recommend a hedge for the $35m investment after a 0.7% rate fall and critically evaluate three directors.','Buying borrower protection for a depositor’s falling-rate exposure.','Investment-return comparison and separate responses to the directors.'),
('Mackosso / Ade','Acquisitions','Acquisition payment; seller gain; integration','Calculate Ade shareholder gains under all three proposals and justify preference. Explain acquisition failure risks.','Skipping one proposal or comparing percentages with different starting valuations.','Three comparable gain estimates and an explained seller preference.')]),
('MJ26','March_June_2026_Exam_Paper',4,[
('Pittu','Treasury','FX futures; margin; dividend capacity','Evaluate the project hedge, daily margin, dividend capacity/shortfall and alternative hedges and dividend policy.','Treating refundable margin as a permanent hedge expense.','Contract and margin schedules, cash-based dividend capacity and policy report.'),
('Colmcille','Capital and valuation','Divestment; asset beta; asset valuation; FCFE','Distinguish sell-off and demerger, discuss shareholder benefits, extract divisional beta and compare valuations.','Using the group beta directly for a division with a different business mix.','Unbundling discussion, beta decomposition and two disposal values.'),
('Trimpley / Rushock','Acquisitions','MBI; FCFE; maximum offer; scenarios','Evaluate the MBI and calculate maximum offer and acquirer share gain/loss in both acquisition scenarios.','Using only the favourable scenario to justify the price.','Two valuations, two price ceilings, per-share effects and assumptions.')]),
('MS26','Pre_September_2026_Mock_Exam',4,[
('Helios','Investment','APV; project beta; tax; VaR; sensitivity','Compare APV with NPV, estimate a project discount rate, base NPV, financing effects and risk sensitivities.','Using revenue weights as if they were observed market-value weights without disclosure.','Beta and cash-flow schedules, APV bridge, VaR and sensitivity interpretation.'),
('Valdero / Fenwick','Acquisitions','Vertical integration; PE; cash offer; share offer','Explain vertical-integration value and compare value creation and transfer under cash and share offers.','Ignoring the cash payment when calculating remaining acquirer wealth.','Standalone and combined values, offer gains for both shareholder groups.'),
('Novara','Treasury','FX futures; OTC hedge; IR futures; options','Recommend an FX payment hedge and compare interest-rate hedges under both 0.9% rate changes.','Using one rate outcome to recommend an option without evaluating the other.','FX comparison plus two interest-rate scenarios and a justified recommendation.')])]
deep={'SP-Q1':98,'D22-Q2':49,'P1-Q1':33,'SD23-Q1':98,'P2-Q2':49,'MJ24-Q1':33,'SD24-Q1':98,'MJ25-Q3':49,'SD25-Q2':33}
questions=[];papers=[]
for code,stem,day,qs in rows:
 p=root/'cr/outputs'/('AFM_'+stem+'.md');text=p.read_text(); matches=list(re.finditer(r'^## Question (\d)[^\n]*',text,re.M));assert len(matches)==3
 title=text.splitlines()[0].lstrip('# ');papers.append(dict(code=code,title=title,day=day,file=p.name))
 for i,(name,topic,methods,summary,pitfall,deliverable) in enumerate(qs):
  m=matches[i];end=matches[i+1].start() if i<2 else len(text); qtext=text[m.start():end]; req=re.search(r'^### Requirements[^\n]*\n',qtext,re.M);assert req
  # Trim structural instructions that sit between questions, retaining every requirement.
  reqtext=re.split(r'\n(?:# Section B|## Section B)',qtext[req.end():])[0].rstrip('\n- ')
  qid=f'{code}-Q{i+1}';startline=text[:m.start()].count('\n')+1; reqline=text[:m.start()+req.start()].count('\n')+1
  questions.append(dict(id=qid,paper=code,paperTitle=title,name=name,q=i+1,marks=50 if i==0 else 25,day=day,topic=topic,methods=methods,summary=summary,pitfall=pitfall,deliverable=deliverable,source=p.name,line=startline,requirementLine=reqline,requirements=reqtext,full=qtext,deepMinutes=deep.get(qid,0),mode='Timed full rehearsal' if code=='MS26' else ('Exposure + deep practice' if qid in deep else 'Exposure + retrieval')))
 (out/'papers'/p.name).write_bytes(p.read_bytes())
 assert hashlib.sha256(p.read_bytes()).digest()==hashlib.sha256((out/'papers'/p.name).read_bytes()).digest()
data=dict(papers=papers,questions=questions)
(out/'.build/data.json').write_text(json.dumps(data,ensure_ascii=False,indent=2))
print('42 source questions coded:',len(questions));print(collections.Counter(q['topic'] for q in questions))
