import json,math
from pathlib import Path
out=Path('/Users/timboi/Documents/Codex/2026-09-05/afm-classroom'); data=json.loads((out/'.build/data.json').read_text())
E='https://www.accaglobal.com/gb/en/student/exam-support-resources/professional-exams-study-resources/p4/introduction/advanced-financial-management-essentials-on-one-page.html'
R="https://www.accaglobal.com/content/dam/acca/global/PDF-students/acca/p4/examinersreports/J24%20AFM%20examiner%27s%20report.pdf"
A='https://studentaccountant.accaglobal.com/2025/04/28/afm-qcl/content.html'
L=[]
def lesson(title,body,prompt,answer,refs,day=1,hint='Name the cash flow, decision and time point before calculating.'):
 L.append(dict(title=title,body=body,prompt=prompt,answer=answer,refs=refs,day=day,hint=hint))
lesson('AFM classroom','Fourteen papers. Forty-two questions.\nReadiness checkpoint: Wednesday 9 September.\nExam: Friday 11 September 2026.','What evidence would show that you can answer a question independently?','A blank-page approach, a valid calculation, a case-based judgement and a successful later retry. Completion ticks measure exposure, not mastery. This classroom is teaching guidance, not an official answer book.',[],hint='Distinguish recognition from retrieval.')
lesson('The study loop','Read the requirement and locate its evidence.\nAttempt the method before opening hints.\nCompare, record one error, then retry later.','In 90 seconds, outline one question without reading its answer.','For each 12-minute exposure: 3 minutes requirements/exhibits, 4 minutes a calculation setup or numerical checkpoint, 3 minutes a case-based paragraph, 2 minutes error and confidence record. Deep practice adds full workings. Revisit after a break and the following day.',[],hint='State what the board needs to decide.')
lesson('Exam output and timing','195 minutes for 100 marks.\nSection A: 50 marks. Section B: 25 + 25.\nProfessional skills account for 20 marks.','How long will you allow for a 25-mark question?','About 49 minutes: 195 × 25/100 = 48.75. A 50-mark question gets about 98 minutes. These budgets include planning and review. Skills are demonstrated through the answer, not a separate 20-minute skills section.',[E,A],hint='Allocate time by the full question marks.')
lesson('The board report','To, from, date and a useful subject.\nHeadings that match the requirements.\nWorkings with units, followed by interpretation.\nA conclusion supported by your own results.','How would you turn “PPP may be wrong” into an evaluative point?','Example teaching wording: PPP may not hold over the project horizon. If the overseas currency weakens more than forecast, home-currency receipts and NPV fall. I would test a downside exchange-rate case before committing. Adapt direction to the actual quotation and exposure.',[R+'#page=8',A],hint='Explain how the assumption changes the decision.')
lesson('The recurring work','Treasury: 13 questions. Acquisitions: 12.\nInvestment: 11. Capital and valuation: 4.\nPerformance: 2. All require applied judgement.','Why should you still practise the two performance questions?','These are counts of primary teaching categories in the supplied 42-question corpus. They are not forecasts of exam frequency. Low frequency does not mean low importance, and every live question is compulsory.',[],hint='The corpus is a study map, not a prediction.')
lesson('Project cash-flow timeline','Time 0: assets and initial working capital.\nOperating years: incremental cash and tax.\nFinal year: disposal and working-capital release.\nLater years: any delayed tax settlements.','Which belongs in NPV: working-capital balance or its change?','Use changes in the required balance, with a cash outflow for an increase and an inflow for a reduction. Release the remaining balance at the end if recoverable. Exclude sunk costs. Keep financing separate when the discount rate already reflects financing.', ['P1-Q1','MS26-Q1'],hint='A balance is an amount tied up. A change is a cash movement.')
lesson('Helios: working capital','Initial working capital is $12m.\nAt the start of Years 2–4, it is 18% of sales.\nYear 2 sales are $44m, then grow by 15%.','Calculate the cash flow at the end of Year 1 and the release at the end of Year 4.','Teaching calculation, $m: required balances at t0,t1,t2,t3 are 12, 7.92, 9.108, 10.4742. Cash movements are −12, +4.08, −1.188, −1.3662, then +10.4742 at t4. The first adjustment releases cash even though later sales grow.', ['MS26-Q1'],hint='18% × 44 = 7.92. Compare that with the existing 12.')
lesson('International investment','Forecast nominal cash flows in local currency.\nCalculate local tax and remittance restrictions.\nTranslate remittances at forecast exchange rates.\nAdd incremental parent cash flows and home tax.','With a quote of foreign currency per home unit, which inflation rate goes on top in PPP?','S(t)=S(0)×[(1+foreign inflation)/(1+home inflation)]^t. Divide foreign cash by S(t) to obtain home cash. For the inverse quotation, invert the relation. Separate genuine parent contribution from a transfer already charged to the subsidiary.', ['SP-Q2','SD23-Q1','SD25-Q1'],hint='Higher foreign inflation should reduce the foreign currency’s purchasing power.',day=2)
lesson('Tax and terminal value','Accounting depreciation is not a cash outflow.\nTax allowances change the tax calculation.\nTax timing follows the question’s payment rule.\nDisposal can trigger a balancing adjustment.','Why can a four-year project have a cash flow in Year 5?','Tax paid one year in arrears creates a t5 settlement for Year 4 operating tax and any taxable balancing adjustment. Helios has this timing. The $22m equipment value is already within the $48m project disposal value, so adding both would double count.', ['MS26-Q1'],hint='Read the words “payable one year in arrears”.')
lesson('Risk and the discount rate','Ungear the comparator’s equity beta.\nIsolate the relevant business activity.\nUse the asset beta for an all-equity base case.\nRegear only when the valuation method requires it.','Write the zero-debt-beta formula and explain the market values.','βa=βe E/[E+D(1−T)]. CAPM: ke=rf+βe×market risk premium. Use βa in CAPM to estimate an ungeared return. Market equity and debt represent investor exposures. An overall mixed-company beta may not represent the new project.', ['SP-Q1','MS26-Q1','MJ26-Q2'],hint='The tax adjustment belongs with debt in this formula.')
lesson('APV separates financing effects','Base NPV uses an ungeared discount rate.\nAdd the present value of financing benefits.\nDeduct issue costs at their payment date.\nDisclose the discount rate for each benefit.','Robson has βa=1.222, rf=3% and market premium=9%. What is its base discount rate?','Teaching calculation: ku = 3% + 1.222×9% = 13.998%, about 14%. Base NPV = −120 +20.9/1.14 +20.6/1.14² +28.7/1.14³ +104.6/1.14⁴ = approximately −$4.51m. This is not the completed APV. Financing benefits and issue costs still need separate schedules.', ['P2-Q2'],day=2,hint='Use the asset beta directly for the all-equity base case.')
lesson('APV financing traps','Interest tax shields follow outstanding debt.\nSubsidies compare equivalent market borrowing.\nIssue-cost grossing depends on funding terms.\nTax relief timing follows the stated rules.','Why does Helios need gross funding of more than $87m?','Its $75m asset investment plus $12m initial working capital require $87m net. With costs of 3.5% of gross finance, gross finance = 87/0.965 = $90.1554m, so issue costs = $3.1554m. Robson’s issue costs come from reserves, so the same gross-up must not be imposed automatically. Avoid double counting subsidy tax effects and tax shields.', ['MS26-Q1','P2-Q2'],day=2,hint='Net proceeds = gross finance × (1 − issue-cost rate).')
lesson('Real options','Expansion or delay often behaves like a call.\nAbandonment at a guaranteed price behaves like a put.\nThe asset is the cash flows subject to that choice.\nThe exercise price is the cash paid or received.','Jigu’s NPV is $10m in Year 4 and its investment is $60m then. What is its asset value today?','Teaching calculation: operating value at Year 4 = 10+60 = $70m. Discount at 11% for four years: 70/1.11⁴ = $46.1112m. The question supplies the accurate call value of $15.3m. The call replaces the value of the flexible opportunity, so do not add both the stand-alone project NPV and the full call value for the same opportunity.', ['P1-Q1'],hint='NPV equals the operating asset value less the investment cost.')
lesson('BSOP input discipline','Pa: present value of relevant underlying cash flows.\nPe: exercise cash amount at the decision date.\nt: years to the decision. σ: annual volatility.\nr: risk-free rate in the model convention.','What makes a real-option valuation uncertain in a project?','The underlying project may not be traded. Volatility and future investment cost may be difficult to estimate. Competition or operational constraints can prevent exercise. Explain the consequence for this decision. For a non-dividend-paying underlying, put-call parity is P=C−Pa+Pe×exp(−rt).', ['MJ24-Q2','D22-Q3','P1-Q1'],hint='Connect each assumption to flexibility that may not really exist.')
lesson('Value creation and transfer','Standalone acquirer + target + synergy = combined value.\nTarget gain is consideration less standalone target value.\nAcquirer gain is remaining wealth less its old value.\nCash and share offers distribute value differently.','Why can an EPS increase coexist with a poor acquisition?','EPS is an accounting ratio affected by the P/E ratios, financing and share count. A company can overpay for the target even if EPS rises. Calculate wealth before and after and test whether expected synergies compensate for the premium.', ['SD24-Q2','MJ25-Q1','MS26-Q2'],hint='Separate the size of the pie from how it is divided.',day=2)
lesson('Valdero: the value bridge','Acquirer: 120m shares at $4.10, earnings $34.56m.\nTarget: earnings $9.75m, P/E 10% below acquirer.\nAnnual post-tax synergy: $3.45m.\nCombined P/E equals the old acquirer P/E.','Estimate standalone target equity and total value created.','Teaching calculations, $m: acquirer equity=492. P/E=492/34.56=14.236111. Target equity=9.75×0.9×14.236111=124.921875. Combined equity=(34.56+9.75+3.45)×14.236111=679.916667. Value created=679.916667−492−124.921875=62.994792. This includes the target P/E rerating as well as capitalised synergy.', ['MS26-Q2'],day=2,hint='Apply the P/E discount to the target before combining.')
lesson('Valdero: cash versus shares','Cash: $3.10 for each of 50m target shares.\nShares: 3 new acquirer shares for every 4 target shares.\nCompare the gain for each shareholder group.','Calculate the acquirer gain under cash and the enlarged share price under shares.','Teaching calculations ignoring unspecified costs/financing effects: cash consideration=$155m. Acquirer wealth=679.916667−155=$524.916667m, gain=6.69%. Target gain=(155/124.921875−1)=24.08%. New shares=37.5m. Enlarged price=679.916667/157.5=$4.316931. Acquirer gain=5.29%. Target share consideration=37.5×4.316931=$161.884921m, gain=29.59%. Both cases distribute the same $62.994792m total gain.', ['MS26-Q2'],day=2,hint='Cash leaves the combined value. Share consideration changes ownership.')
lesson('Equity and enterprise value','FCFF discounts at WACC, then bridges to equity.\nFCFE discounts at cost of equity.\nTerminal value belongs at the end of the forecast.\nA multiple needs a comparable earnings basis.','When would subtracting debt be a double count?','When the cash flows are already FCFE and the present value is equity value. FCFF = EBIT(1−T)+depreciation−capital expenditure−increase in working capital. FCFE = profit after tax+depreciation−capital expenditure−increase in working capital+net borrowing. For a constant-growth perpetuity at t=n, TVn=CF(n+1)/(k−g), then discount TVn to today.', ['MJ24-Q3','SD24-Q3','MJ26-Q3'],day=2,hint='Identify whose cash flow you have valued.')
lesson('Bonds and changing capital structure','Coupon and redemption are separate cash flows.\nSpot yield plus credit spread prices each maturity.\nPost-tax debt cost uses net coupon cash flows.\nMarket-value weights drive WACC.','Kingtim has 25m shares at $5.56 and 0.45m bonds at $104. What are its old market weights?','Teaching calculations, $m: E=139 and D=46.8. E/(E+D)=74.8116%, D/(E+D)=25.1884%. ke=4%+0.9×9%=12.1%. With the supplied after-tax kd=4.1%, WACC=10.0849%. For new bonds, price each cash flow at its maturity’s spot rate plus the appropriate credit spread, then solve the after-tax yield. Do not simply tax-adjust a spot curve.', ['SP-Q1'],hint='Count instruments, then multiply by market price.')
lesson('FX hedge direction','Write the exposure in words and currencies.\nChoose the contract currency and maturity.\nMake the derivative gain in the adverse case.\nCompare final home-currency cash flows.','Boullain receives $18.6m. The forward quote is €0.8729–0.8744 per $1. What is the euro receipt?','Teaching calculation: the bank buys dollars at €0.8729, so receipt = $18.6m × €0.8729/$ = €16.236m. With euro contracts quoted in dollars per euro, a dollar recipient needs euros and buys euro futures or calls. Direction is based on contract currency, not a memorised rule about all receipts.', ['SP-Q3'],hint='The bank gives the less favourable side to its customer.')
lesson('FX futures and options','Round contracts exactly as instructed.\nCover residual exposure using the stated method.\nInclude premium in the comparison currency.\nBasis assumptions and margin affect the decision.','Why can a nearly correct futures calculation still miss the hedge outcome?','It may omit the residual or excess cover after rounding, reverse the futures gain, or mix quotation currencies. The March/June 2024 examiner report highlights residual forward cover, hedge direction and rounding. A premium is a cost whether or not the option is exercised. Initial margin is refundable collateral, with liquidity/opportunity costs.', [R+'#page=6','MJ24-Q1','MJ26-Q1'],hint='Reconcile cash-market exposure and derivative proceeds.',day=2)
lesson('Pittu: daily margin','A dollar futures contract is $125,000.\nIt opens at W£3.2200 per dollar.\nDay 1 closes at 3.2230 and Day 2 at 3.2219.\nInitial margin is W£10,000. Maintenance is W£9,750.','For one short contract, find each day’s gain/loss and any top-up.','Teaching calculation per contract: Day 1 loss=(3.2200−3.2230)×125,000= W£375. Balance=9,625, below maintenance, so top up W£375 to 10,000. Day 2 gain=(3.2230−3.2219)×125,000=W£137.50. Balance=10,137.50. Multiply by the contract count used in the full hedge. Margin movements affect liquidity even when the hedge is economically effective.', ['MJ26-Q1'],day=3,hint='Short futures lose when price rises.')
lesson('Interest-rate hedging','Borrower fears a rate rise: short futures or buy puts.\nDepositor fears a rate fall: long futures or buy calls.\nFutures price is 100 minus the annual rate.\nUse exposure months ÷ contract months in sizing.','Lurgshall borrows $84m for six months. Three-month contracts are $2m. How many?','Teaching calculation: 84/2 × 6/3 = 84 contracts. Compare cash interest, futures/option payoff and premium over the six-month loan period. Divide net cost by principal × 6/12 to annualise the effective rate. A basis point is 0.01 percentage points.', ['P1-Q3','SD23-Q3'],hint='The loan lasts twice the contract interest period.',day=3)
lesson('Collars and swaps','A collar combines a bought and written option.\nLower premium sacrifices some favourable movement.\nA swap exchanges interest cash flows on a notional.\nA comparison includes fees and counterparty exposure.','Lurgshall’s fixed-rate gap is 0.5% and floating-rate gap is 1.0%. Each party pays a 0.1% fee. What is each equal net saving?','Teaching calculation: gross comparative advantage = 1.0%−0.5%=0.5%. Total fees =0.2%. Net shared saving =0.3%, hence 0.15% each. Lurgshall’s fixed-rate benchmark is 5.6%, giving 5.45% all-in fixed if it takes that equal saving. Show actual borrowing and swap legs to reconcile the result.', ['P1-Q3','SD24-Q1'],hint='Deduct both parties’ fees before splitting the saving.',day=3)
lesson('Netting and treasury','Convert all balances to one settlement currency.\nTotal each company’s receipts and payments.\nSettle its net amount and reconcile to zero.\nAssess liquidity, controls and remaining exposures.','Does multilateral netting eliminate all foreign-exchange risk?','No. It reduces gross settlements and may reduce transaction costs and the exposure to hedge, but residual currency positions remain. In Mahoney, delayed settlement can strain companies owed significant balances. The examiner report specifically cautions against claiming that netting eliminates all currency risk.', ['MJ24-Q1',R+'#page=6'],day=3,hint='Fewer transfers do not imply zero net exposure.')
lesson('Performance as a business explanation','Calculate a trend or relevant ratio.\nConnect it to evidence in the scenario.\nExplain the financing or shareholder consequence.\nName the missing data needed to test your explanation.','Southmed’s operating profit falls from 9,800 to 7,700 on revenue 121,900 to 120,900. What is the margin change?','Teaching calculation: operating margin falls from 8.0394% to 6.3689%, a decline of 1.6705 percentage points. Profit falls 21.43% while revenue falls 0.82%. This suggests cost pressure beyond the slight sales decline. Competition may limit price increases, but segment-level margins and like-for-like sales are needed to test that explanation.', ['SD23-Q2','MJ25-Q3'],day=3,hint='Distinguish percentage points from percentage change.')
lesson('Dividends, restructuring and ethics','Dividend capacity begins with cash availability.\nA sale and a demerger have different ownership effects.\nSynergy needs an integration mechanism.\nEthical concerns need practical actions.','How would you challenge “the project has positive NPV, so the dividend is safe”?','Positive NPV measures discounted value. It does not guarantee cash at the dividend payment date. In Pittu, calculate the project payment and other cash commitments before dividend capacity and any shortfall. Then discuss shareholder expectations, financing choices and how the board communicates a policy change.', ['MJ26-Q1','MJ26-Q2','SD25-Q2','P1-Q1'],day=3,hint='A profitable project can still create a funding gap.')
lesson('VaR and sensitivity','VaR describes a confidence-level threshold.\nIt is not a worst possible loss.\nTime scaling needs a stated dependence assumption.\nSensitivity asks when NPV changes sign.','Helios has annual cash-flow σ=$1.1m. Estimate a four-year, 95% adverse deviation using z=1.645.','Teaching calculation assuming independent, similarly distributed annual cash-flow uncertainty: 1.645×1.1×√4 = $3.619m below the expected aggregate cash flow. This is an undiscounted cash-flow approximation, not automatically a project-NPV VaR. Correlation, varying annual risk and discounting require a different aggregation. For sensitivity, vary post-tax operating cash flows consistently and re-solve NPV=0 for the cost of capital.', ['MS26-Q1'],day=4,hint='Four independent years scale standard deviation by √4, not 4.')
lesson('A stronger discussion paragraph','Case evidence establishes the issue.\nFinancial reasoning explains its effect.\nScepticism tests the assumption.\nAdvice answers the requirement.','Hav has commercialisation skills and Strand has scientific know-how. Draft a revenue-synergy paragraph.','Teaching example: Hav’s ability to bring products to market could help commercialise Strand’s research and create new sales. The benefit depends on retaining Strand’s scientists and funding viable development. Integration should preserve the research capability and set milestones for product launches. A generic definition of revenue synergy would not make these links.', ['P1-Q2',A],day=2,hint='Connect complementary capabilities to a cash-flow mechanism.')
lesson('Readiness by Wednesday','One 195-minute rehearsal on Tuesday.\nWednesday: another timed paper and careful debrief.\nRetry weak methods from a blank page.\nUse Thursday for short repair and recovery.','What triggers another deep attempt rather than another slide read?','A missing method, wrong exposure direction, repeated timing error, unsupported conclusion, or an answer you cannot reproduce without cues. Readiness is stronger when you can complete the timing, explain your own result and correct recurring errors. Neither coverage nor confidence guarantees a pass.', [],day=4,hint='Use the error log to decide the next action.')
# Paper labs keep all 42 questions visible in the editable deck.
for p in data['papers']:
 qs=[q for q in data['questions'] if q['paper']==p['code']]
 lesson(p['code']+': paper workshop','\n'.join(f"Q{q['q']} {q['name']}: {q['methods'].split(';')[0]}" for q in qs), 'For each question: one method setup, one case paragraph, one error to retry.', '\n\n'.join(q['id']+': '+q['summary']+' Expected output (teaching guidance): '+q['deliverable']+' Watch for: '+q['pitfall'] for q in qs),[q['id'] for q in qs],day=p['day'],hint='Open the original requirement in the classroom library, then use the staged question guide.')
(out/'.build/lessons.json').write_text(json.dumps(L,ensure_ascii=False,indent=2))
print('Lessons',len(L))
# Verify independently recomputed numerical checkpoints.
print('Robson NPV',sum(c/1.14**t for t,c in enumerate([-120,20.9,20.6,28.7,104.6])))
print('Jigu asset',70/1.11**4)
print('Kingtim WACC',(139*12.1+46.8*4.1)/185.8)
